---
version: '2.1'
#volumes:
services:
  api:
    build:
      context: ./api
    image: demo-flask-prom:v0.1-alpha
    ports:
      - "5000:5000"
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    environment:
      - FLASK_APP=/app/api.py
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0"]

  prometheus:
    image: docker.io/prom/prometheus:v2.27.0
    depends_on:
      - api
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:z
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    ports:
      - "9090:9090"

  grafana:
    image: docker.io/grafana/grafana:7.5.6
    depends_on:
      - prometheus
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:z
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:z
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:z
      - ./grafana/dashboards:/var/lib/grafana/dashboards:z
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    ports:
      - "3000:3000"
